name: Publish PDF
on: [push]
permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'publish')
    steps:

      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Release PDF
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          name: ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            build/main.pdf
