name: Publish PDF
on: [push]
permissions:
  contents: write
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'publish')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
        #   pre_compile: "make input"
          root_file: main.tex
          post_compile: "cp build/main.pdf main.pdf"
      - name: Release PDF
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: |
            build/main.pdf
